FROM alpine:3

LABEL author="Melvin Toni Gustave"
LABEL company="PT Toni Gustave" website="https://github.com/melvin-toni"

RUN mkdir hello
RUN echo "Hello World" > "hello/world.txt"

CMD cat "hello/world.txt"